version: '3.3'
services:
  wallet-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini_ewallet_api
    ports:
      - 8080:3000
    volumes:
      - '.:/home/go/src/wallet:rw'
    networks:
      wallet_network:
        ipv4_address: 174.21.210.10
    tty: true
  database:
    image: postgres
    env_file:
      - .env
    ports:
    - 5432:5432
    networks:
      wallet_network:
        ipv4_address: 174.21.210.11
networks:
  wallet_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: 'false'
    ipam:
      driver: default
      config:
      - subnet: 174.21.210.0/24