version: '3.0'
services:
  wallet-db:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-mysql
    container_name: mini_ewallet_db
    environment:
      MYSQL_ROOT_PASSWORD: 'toor'
      MYSQL_USER: 'user_wallet'
      MYSQL_PASS: 'password_wallet'
    # volumes:
    #   - ./data/mysql:/var/lib/mysql
    ports:
      - 3301:3306
  wallet-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini_ewallet_api
    ports:
      - 8080:3000
    volumes:
      - '.:/go/src/wallet:rw'
    tty: true